---
title: "Schedule"
---

**Click on the text like "Week 1: Sep 5 -- 7" to expand or collapse the items we covered in that week.**

I will fill in more detail and provide links to lecture notes and labs as we go along.  Items for future dates are tentative and subject to change.

```{r, echo = FALSE}
make_week_box <- function(id, open, title, contents) {
  cat('
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h5 class="mb-0">
<a data-toggle="collapse" href="#',
id,
'" aria-expanded="true" aria-controls="collapseOne">
',
title,
'</a>
</h5>
</div>

<div id="',
id,
'" class="collapse',
ifelse(open, " in", ""),
'">
<div class="panel-body">
',
contents,
'
</div>
</div>
</div>',
  sep = "")
}
```

```{r, echo = FALSE, results='asis'}
make_week_box("week1", FALSE, "Week 1: Sep 5 -- 7",
"Chapters 1-3: Overview, Review of Simple Linear Regression, Polynomial Regression, MSE, Bias/Variance Trade-off, Train/Test Errors

#### Wed, Sept 5

 * **In class**, we will work on:
    * Material from: Chapter 1, Section 2.1, Section 2.2.1, and Section 3.1 of ISLR
    * Overiew of the Class: slides [pdf](materials/20180904_intro/20180904_slides_class_overview.pdf)
    * Notation
    * Mini-demo and reminder about Simple Linear Regression, estimation via ordinary least squares
        * Warmup: [pdf](materials/20180904_intro/20180904_slr_warmup.pdf)
        * Summary of R commands and interpretation for SLR: [pdf](materials/20180904_intro/201800904_SLR_summary.pdf)
        * Code for later:  
`beer <- read.csv(\"http://www.evanlray.com/data/openintro/bac.csv\")`  
`beer`  
`source(\"http://www.evanlray.com/stat340_f2018/materials/20180904_intro/plot_ss.R\")`  
`plot_ss(beer$Beers, beer$BAC)`  
    * Set up GitHub accounts and RStudio
        * Video overview: [https://www.youtube.com/watch?v=YxZ8J2rqhEM](https://www.youtube.com/watch?v=YxZ8J2rqhEM)
        * Pdf with detailed instructions: [pdf](resources/Stat340-github-setup.pdf)
 * **After class**, please:
    * Finish the activity from class about setting up your GitHub account on RStudio, if you didn't finish this in class.  **This must be done before class on Friday!**  If you run into trouble, come by my office and we will sort it out!
    * **Fill Out** this survey about when my office hours should be held: [http://whenisgood.net/y7js2rh](http://whenisgood.net/y7js2rh)
    * **Register** for Piazza at [https://piazza.com/mtholyoke/fall2018/stat340](https://piazza.com/mtholyoke/fall2018/stat340)
    * **Read**:
        * Chapter 1 of ISLR
        * Sections 2.1, 2.2.1, and 2.2.2 of ISLR (Section 2.2.3 will be discussed in a few weeks)
        * Section 3.1 of ISLR
        * The part of 3.3.2 titled \"Non-linear Relationships\" of ISLR
        * Handout about Simple Linear Regression
    * **Post Questions** about Simple Linear Regression on Piazza if you have them (anonymously if you want!).  It's ok to not remember stuff or understand it fully from the reading!  It's not ok to be confused in silence.
    * **Homework 1**: Complete 4 [DataCamp](https://www.datacamp.com) chapters from the Introduction to R course: Intro to basics, Vectors, Factors, and Data frames.  You will get an email by the end of the day on Sept 5 inviting you to join our class organization with assignments pointing you to the specific chapters to do.  You should **feel free to work on this in groups** -- but please **each complete your own copy of this assignment**!  Your grade on this assignment is only for completion, not correctness.  If you get stuck, post a message on Piazza!  I don't expect you to remember everything or feel like an expert at it; we will continue working on this over the rest of the semester.  This is just a first introduction.  If you have done these chapters for a previous class, you don't need to do them again.

#### Fri, Sept 7
  * **In class**, we will work on:
    * Material from: Section 2.2.2, 3.1, and the part of 3.3.2 titled \"Non-linear Relationships\" of ISLR (to be continued next week)
    * How do we estimate the coefficients in simple linear regression? (By minimizing the sum of squared residuals, SSR)
    * Polynomial regression: [pdf](materials/20180907_polynomial_train_test/20180907_polynomial_regression.pdf)
    * First thoughts about graphical and numeric comparison of candidate models.
        * Example 1: [pdf](materials/20180907_polynomial_train_test/20180907_train_test_Example_1.pdf)
        * Example 2: [pdf](materials/20180907_polynomial_train_test/20180907_train_test_Example_2.pdf)
        * Example 2 Wrapup: [pdf](materials/20180907_polynomial_train_test/20180907_train_test_Example_2_wrapup.pdf)
    * Train/Test Set Errors
 * **After class**, please:
    * **Read**:
        * Sections 3.2, 3.3, and 3.4 of ISLR (we will be discussing these throughout next week, not all on Monday)
        * Chapter 3 of R4DS: http://r4ds.had.co.nz/data-visualisation.html
    * **Homework**:
        * Finish **Homework 1** if not done yet
        * **Homework 2 due Wednesday, Sept 12**: Data Camp assignment about ggplot2
"
)
```

```{r, echo = FALSE, results='asis'}
make_week_box("week2", FALSE, "Week 2: Sep 10 -- 14",
"
Chapter 3: Multiple Regression

#### Mon, Sep 10
  * **In class**, we will work on:
    * Mean Squared Error and the Bias-Variance Trade-Off.
        * Motivational example: [pdf](materials/20180910_MSE_Bias_Var_Pairs_Plots/20180910_Example_2_MSE_Bias_Variance.pdf)
        * Lecture Notes: [pdf](materials/20180910_MSE_Bias_Var_Pairs_Plots/lecture_notes.pdf)
    * Pairs plots with `GGally::ggpairs`.  [pdf](materials/20180910_MSE_Bias_Var_Pairs_Plots/20180910_Pairs_Plots.pdf)
    * Lab01 (go to https://github.com/mhc-stat340-f2018 to find your repository)
 * **After class**, please:
    * **Read**:
        * Sections 3.2, 3.3, and 3.4 of ISLR (we will be discussing these throughout this week)
        * Chapter 3 of R4DS: http://r4ds.had.co.nz/data-visualisation.html
    * **Homework**:
        * **Homework 2 due Wednesday, Sept 12**: Data Camp assignment about ggplot2
        * **Homework 3 due Wednesday, Sept 19**: Assigned on GitHub

#### Wed, Sep 12
 * **In class**, we will work on:
    * Multiple Linear Regression with quantitative explanatory variables: [pdf](materials/20180912_Multiple_Regression_Quant_X/20180912_Multiple_Regression_Quant_X.pdf)
    * Lab 02: multiple linear regression with quantitative variables.  Go to https://github.com/mhc-stat340-f2018 to find your repository.
 * **After class**, please:
    * **Homework**:
        * **Homework 3 due Wednesday, Sept 19**

#### Fri, Sep 14
 * **In class**, we will work on:
    * Overview of methods to plot estimated lines/curves using `ggplot2`: [pdf](materials/20180914_plotting_estimated_lines/20180914_plotting_estimated_lines.pdf)
    * Lab 02: multiple linear regression with quantitative variables.  Go to https://github.com/mhc-stat340-f2018 to find your repository.
 * **After class**, please:
    * **Homework**:
        * **Homework 3 due Wednesday, Sept 19**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week3", FALSE, "Week 3: Sep 17 -- 21",
"
Finishing Chapter 3

#### Mon, Sep 17
 * **In class**, we will work on:
    * Multiple Linear Regression with both quantitative and categorical explanatory variables: [pdf](materials/20180917_Multiple_Regression_Cat_X/20180917_Multiple_Regression_Cat_X.pdf)
    * Lab 03 about multiple linear regression with both quantitative and categorical explanatory variables.  Go to https://github.com/mhc-stat340-f2018 to find your repository.
 * **After class**, please:
    * **Homework**:
        * **Homework 3 due Wednesday, Sept 19**

#### Wed, Sep 19
 * **In class**, we will work on:
    * Q-Q plots: [pdf](materials/20180919_transformations/20180917_QQ.pdf)
    * Transformations to approximate normality [pdf](materials/20180919_transformations/20180917_Transformations.pdf)
    * Start on labs 3 and 4.  Go to https://github.com/mhc-stat340-f2018 to find your repository.
 * **After class**, please:
    * **Homework 4 due Friday, Sept 28** - hope to post on Thursday Sep 20?

#### Fri, Sep 21
 * **In class**, we will work on:
    * Review Homework 3
    * Finish labs 3 and 4.  Go to https://github.com/mhc-stat340-f2018 to find your repository.
 * **After class**, please:
    * **Read**:
        * Section 3.5 of ISLR
    * **Homework 4 due Friday, Sept 28**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week4", FALSE, "Week 4: Sep 24 -- 28",
"
Section 3.5, start on Sections 2.2.3 and Sections 4.1 through 4.3: Foundations for Classification, Logistic Regression

#### Mon, Sep 24
 * **In class**, we will work on:
    * **Quiz** on contents of Homework 3
    * Finish Lab 04 (data transformations)
    * Start on non-parametric regression with K nearest neighbors [pdf](materials/20180924_KNN/20180924_KNN.pdf)
 * **After class**, please:
    * **Read**:
        * Sections 2.2.3 and 4.1 through 4.3 of ISLR
    * **Homework 4 due Friday, Sept 28**

#### Wed, Sep 26
 * **In class**, we will work on:
    * A couple more comments about non-parametric regression with K nearest neighbors
    * Briefly, motivating examples for classification: [pdf](materials/20180926_intro_classification/20180926_classification_motivation.pdf)
    * Start thinking about classification for 2 classes via logistic regression: [pdf](materials/20180926_intro_classification/20180926_logistic_intro.pdf)
    * Lab 05 on Gryd: Logistic regression with one explanatory variable.  
 * **After class**, please:
    * **Homework 4 due Friday, Sept 28**

#### Fri, Sep 28
 * **Homework 4** due today!
 * **In class**, we will work on:
    * Review Quiz (make ups will be allowed for up to 50% of the credit you missed the first time).
    * Code for KNN
    * Finish Lab 05
 * **After class**, please:
    * **Homework 5 and Homework 6 due Friday, Oct 5**
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week5", FALSE, "Week 5: Oct 1 -- 5",
"
Section 2.2 and Sections 4.1 - 4.3: Intro. to Classification, Multiple Logistic Regression

#### Mon, Oct 1
 * **In class**, we will work on:
    * Overview of HW 4
    * Intro to classification for 2 classes via (multiple) logistic regression. [pdf](materials/20181001_multiple_logistic_regression/20181001_multiple_logistic.pdf)
    * Finish Lab 05, start Lab 06
 * **After class**, please:
    * **Homework 5 and Homework 6 due Friday, Oct 5**

#### Wed, Oct 3
 * **In class**, we will work on:
    * Finish talking through multiple logistic regression handout from last time: categorical explanatory variables
    * Parameter interpretation and hypothesis tests in logistic regression models: [pdf](materials/20181003_multiple_logistic_interpretation_tests/20181003_multiple_logistic_interpretation_tests.pdf)
    * Finish Lab 06, Start Lab 07
 * **After class**, please:
    * **Homework 5 (GitHub) and Homework 6 (Data Camp) due Friday, Oct 5**

#### Fri, Oct 5
 * **Homework 5 (GitHub) and Homework 6 (Data Camp) due today!**
 * **In class**, we will work on:
    * Bayes classifier/Bayes error rate
    * Overview of estimation for logistic regression (see Stat 343 for more)
    * Finish Lab 07
 * **After class**, please:
    * Prepare for a quiz on regression on Wednesday, Oct 10.  See quizzes page on website for topics.
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week6", FALSE, "Week 6: Oct 8 -- 12",
"
Section 2.2

#### Mon, Oct 8
 * **No Class**: mid-semester break.  Safe travels!

#### Wed, Oct 10
 * **In class**, we will work on:
    * Quiz on multiple regression.  See quizzes page on website for topics.
    * Overview/review of Lab 07
    * Start thinking about KNN Classification: [pdf](materials/20181009_KNN_class/20181009_KNN_class.pdf)
    * Notes: [pdf](materials/20181009_KNN_class/20181010_notes.pdf)
 * **After class**, please:
    * Take-home midterm distributed; due Monday Oct 15

#### Fri, Oct 12
 * **In class**, we will work on:
    * Finish thinking about KNN Classification (handout from last class)
    * Review of `dplyr::mutate` and `dplyr::filter`
        * RStudio Data Wrangling Cheat Sheet: [pdf](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
    * Lab 08
 * **After class**, please:
    * Take-home midterm due Monday Oct 15
    * Homework 07 due Monday Oct 22
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week7", FALSE, "Week 7: Oct 15 -- 19",
"
Sections 5.1 and 6.1: Cross-validation and Variable Selection Methods

#### Mon, Oct 15
 * **Midterm Due Today!**
 * **In class**, we will work on:
    * Overview of the `purrr::map` and `purrr::pmap` family of functions: [pdf](materials/20181015_map_pmap/20181015_map_pmap.pdf)
    * Finish Lab 08: KNN Classification
    * Lab 09: Practice with `map` and `pmap`
 * **After class**, please:
    * Read ISLR Section 5.1
    * Homework 07 due Monday Oct 22

#### Wed, Oct 17
 * **In class**, we will work on:
    * Old labs (8 and 9)
    * Cross-validation for model selection: [pdf](materials/20181017_crossvalidation/20181017_crossvalidation.pdf)
 * **After class**, please:
    * Read ISLR Section 6.1
    * Homework 07 due Monday Oct 22

#### Fri, Oct 19
 * **In class**, we will work on:
    * Cross-validation and other approaches to model selection
 * **After class**, please:
    * Homework 07 due Monday Oct 22
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week8", FALSE, "Week 8: Oct 22 -- 26",
"
Sections 6.1 and 6.2: Variable Selection and Shrinkage Methods.

#### Mon, Oct 22
 * **Homework 07 Due Today!**
 * **In class**, we will work on:
    * Lab 10, about cross-validation

#### Wed, Oct 24
 * **In class**, we will work on:
    * Section 6.1: AIC, BIC, Cp, $R^2_{adj}$, and stepwise variable selection procedures. [pdf](materials/20181024_variable_selection/20181024_variable_selection.pdf)
    * Section 6.2: Shrinkage/Regularization.  [pdf](materials/20181024_variable_selection/20181024_shrinkage.pdf)

#### Fri, Oct 26
 * **In class**, we will work on:
    * Finish discussion of shrinkage/regularization.
    * Lab 11: LASSO and Ridge regression
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week9", FALSE, "Week 9: Oct 29 -- Nov 2",
"
Start on Chapter 8: Tree-Based Methods and Ensembles

#### Mon, Oct 29
 * **In class**, we will work on:
    * **Quiz** on material from Chapter 4 (classification).  See quizzes page for topics.
    * Discuss final project
    * Finish Lab 11
* **After class**, please work on:
    * Lab 09: due as 1/2-value homework assignment on Friday Nov 2
    * PS 08: due Friday Nov 2

#### Wed, Oct 31
 * **In class**, we will work on:
    * Introduce Classification and Regression Trees: [pdf](materials/20181029_trees/20181029_trees.pdf)
 * **After class**, please work on:
    * Lab 09: due as 1/2-value homework assignment on Monday Nov 5
    * PS 08: due Monday Nov 5

#### Fri, Nov 2
 * **In class**, we will work on:
    * Introduction to Ensembles [pdf](materials/20181102_intro_ensembles/20181102_stacking_ionosphere.pdf)
 * **After class**, please work on:
    * Lab 09: due as 1/2-value homework assignment on Monday Nov 5
    * PS 08: due Monday Nov 5
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week10", TRUE, "Week 10: Nov 5 -- 9",
"
Chapter 8: Tree-Based Methods

#### Mon, Nov 5
 * **In class**, we will work on:
    * Merge conflicts in git: [pdf](materials/20181105_stacking_regression/Stat340-github-conflicts.pdf)
    * Ensembles and stacking for regression: [pdf](materials/20181105_stacking_regression/20181105_stacking_regression.pdf)
 * **After class**, please work on:
    * Lab 09: due today
    * PS 08: due today

#### Wed, Nov 7
 * **In class**, we will work on:
    * Random forests: [pdf](materials/20181109_rf/20181109_rf.pdf)
    * Start lab about stacking and random forests

#### Fri, Nov 9
 * **First steps on project due today: see projects page**
 * **In class**, we will work on:
    * Finish lab about stacking and random forests
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week11", TRUE, "Week 11: Nov 12 -- 16",
"
Gradient Tree Boosting

**Midterm 2 this week** - take home, due Tuesday Nov 20.

#### Mon, Nov 12
 * Overview of ideas so far: [pdf](materials/20181112_overview_missing/overview.pdf)
 * Imputing Missing Data: [pdf](materials/20181112_overview_missing/20181112_missing_data.pdf)

#### Wed, Nov 14
 * Start on Gradient Tree Bosting: [pdf](materials/20181114_intro_gradient_boosting/20181114_intro_gradient_boosting.pdf)
 * Time for working on projects

#### Fri, Nov 16
 * Lab on Gradient Tree Boosting
 * Time for working on projects
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week12", FALSE, "Week 12: Nov 19 -- 23 (Thanksgiving)",
"
More on Gradient Tree Boosting; Thanksgiving Break

#### Mon, Nov 19

#### Wed, Nov 21
* **No Class**: Thanksgiving break.  Safe travels!

#### Fri, Nov 23
* **No Class**: Thanksgiving break.  Safe travels!
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week13", FALSE, "Week 13: Nov 26 -- 30",
"
Chapter 7: Splines and GAMs

#### Mon, Nov 26

#### Wed, Nov 28

#### Fri, Nov 30
"
)
```

```{r, echo = FALSE, results='asis'}
make_week_box("week14", FALSE, "Week 14: Dec 3 -- 7",
"
Projects and Project Presentations

#### Mon, Dec 3

#### Wed, Dec 5

#### Fri, Dec 7
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("week15", FALSE, "Week 15: Dec 10",
"

#### Mon, Dec 10
"
  )
```

```{r, echo = FALSE, results='asis'}
make_week_box("finals", TRUE, "Final Exams: Fri, Dec 14 at 7pm -- Tue, Dec 18 at noon",
"We will NOT have a cumulative final exam.
"
  )
```
